package house.with.swimmingpool.models.request

data class FilterObjectsRequest(
    var advantages: List<String>? = null,
    var buildingClass: List<String>? = null,
    var completed: Boolean? = null,
//    var deadline: List<Str>?,
    var dir: String? = null,
    var districts: List<String>? = null,
    var extend: Boolean? = null,
    var interiorTypes: List<String>? = null,
    var limit: Int = 1000,
    var microDistricts: List<String>? = null,
    var new: Boolean? = null,
    var paymentTypes: List<String>? = null,
    var popular: Boolean? = null,
    var price_all_from: String? = null,
    var price_all_to: String? = null,
//    var price_day_from: String?,
//    var price_day_to: String?,
//    var price_month_from: String?,
//    var price_month_to: String?,
//    var price_sq_from: String?,
//    var price_sq_to: String?,
    var recommended: Boolean? = null,
    var registrationTypes: List<Any>? = null,
    var seaDistance: Int? = null,
    var sort: String? = null,
    var square_all_from: String? = null,
    var square_all_to: String? = null,
//    var square_area_from: String?,
//    var square_area_to: String?,
    var start: Int = 0,
    var types: List<String>? = null
)